---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-topics-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: kafka-topics-controller
    app.kubernetes.io/name: kafka-topics-controller
