---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: kafkatopics.pincette.net
spec:
  group: pincette.net
  names:
    kind: KafkaTopic
    plural: kafkatopics
    singular: kafkatopic
  scope: Namespaced
  versions:
    - additionalPrinterColumns:
        - jsonPath: .status.health.status
          name: Health
          type: string
        - jsonPath: .status.phase
          name: Phase
          type: string
      name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                maxMessageBytes:
                  type: integer
                name:
                  type: string
                partitions:
                  type: integer
                replicationFactor:
                  type: integer
                retentionBytes:
                  type: integer
                retentionMilliseconds:
                  type: integer
              type: object
            status:
              properties:
                conditions:
                  items:
                    properties:
                      lastTransitionTime:
                        type: string
                      message:
                        type: string
                      reason:
                        type: string
                      status:
                        type: string
                      type:
                        type: string
                    type: object
                  type: array
                health:
                  properties:
                    status:
                      type: string
                  type: object
                messageLag:
                  additionalProperties:
                    additionalProperties:
                      type: integer
                    type: object
                  type: object
                phase:
                  type: string
              type: object
          type: object
      served: true
      storage: true
      subresources:
        status: {}
